[package]
name = "keepers-relay-participant-type"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Keepers Relay Participant Entry type script"

[dependencies]
ckb-std = { workspace = true }
keepers-relay-protocol-common = { path = "../protocol-common" }

[[bin]]
name = "participant-type"
path = "src/main.rs"
