[workspace]
resolver = "2"

members = [
  # @@INSERTION_POINT@@
  "contracts/chain-cell-type",
  "tests",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
ckb-std = { version = "=1.1.0", default-features = true }

[profile.release]
overflow-checks = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
