[package]
name = "keepers-relay-event-type"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Keepers Relay Event type script v3"

[dependencies]
ckb-std = { workspace = true }
keepers-relay-protocol-common = { path = "../protocol-common" }

[[bin]]
name = "event-type"
path = "src/main.rs"
